---
apiVersion: v1
kind: Pod
metadata:
  name: dkube-installer
spec:
  containers:
  - name: dkube-installer-ctr
    image: ocdr/dkubeadm:2.0.7.1
    command: 
    - bash
    - -c
    - |
      echo "Hello World..."
      sleep 1000000000000000
    volumeMounts:
      - 
        mountPath: /root/.dkube
        name: dkubeini
  volumes:
    - 
      configMap:
        name: dkube-ini
      name: dkubeini
